### ISSUE TITLE
When changing the language the counter starts from 10 again

### ISSUE THREAD

**Issue by lauratbg** [Arquisoft/wiq_en1b#100]

**Comment by uo289267** [comment]
changeLanguage is a function provided from i18n component and maybe in the act of trying to change the language the countdown is being reloaded to with its original status. I think the solution would be to unable the cb or menu item of Language so it cannot be clicked once you have started a game, not only because the countdown behaves strangely but also because it is not feasible to load the questions in another language in the middle of a game (at the end right now it is no possible that you are playing a game and you change the language on the go, this is because the questions are being loaded all at once and for one single language).

**Comment by lauratbg** [comment]
Trying do disable the language button in question view

**Comment by lauratbg** [comment]
Solved 
  const isQuestionsPage = location.pathname === '/questions';

![image](https://github.com/Arquisoft/wiq_en1b/assets/78926547/a074e52c-2336-4af5-9ae0-7aea5fe93979)
