### ISSUE TITLE
Erdem's Self Report - Third Deliverable

### ISSUE THREAD

**Issue by UO289845** [Arquisoft/wiq_en1b#76]

**Comment by ErdemYabaci** [comment]
For the third delivery, I had to update question generation methods, making them compatible with random entity generator for more randomness, instead of fixed entity list. And I had to work on openapi documentation.
Issues that were I was a part of:
* #58 

And I've worked in the branches:
* [Question_Generation_Distractors](https://github.com/Arquisoft/wiq_en1b/tree/Question_Generation_Distractors)
* [Question_Generation_General](https://github.com/Arquisoft/wiq_en1b/tree/Question_Generation_General)
* [openapi_documentation](https://github.com/Arquisoft/wiq_en1b/tree/openapi_documentation)

Also, I have participated in the pull requests:
* #80 
* #67 
* #70 
* #82 

Finally, I have taken part in the following minutes:
* [Ninth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Ninth%E2%80%90Meeting)
* [Tenth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Tenth%E2%80%90Meeting)
* [Twelfth Meeting](https://github.com/Arquisoft/wiq_en1b/wiki/Twelfth-Meeting)
